#!/usr/bin/env bash

SAVE=smearing-script-new

#Print a gnuplot script to plot the 2 column files
##!/usr/bin/gnuplot
cat > plot-smearing-script-new.gnu <<EOF
#!/opt/local/bin/gnuplot

# x11 should work on any system
# try wxt (ubuntu) or aqua (mac) for nicer plots
set term x11 enhanced
set out

set xlabel "k-grid (NxNx1)"
set ylabel "E_{tot} (Ry)
Emin=-22.15272303
thres_1mRy_per_atom=0.001*2
thres_10mRy_per_atom=0.01*2
list="3x3x1 6x6x1 9x9x1 12x12x1"
list="0.003 0.01 0.05 0.1 0.2"
item(n) = word(list,n)

set xtics 3
set mxtics 3
set xrange [1:13]
set yrange [-22.18:-22.10]
set multiplot layout 1,2
set title "Smearing: gaussian"
plot for [p=1:5] "Etot_vs_kgrid-script-new.dat_gaussian" index p-1 u 3:5 w lp title item(p)
set title "Smearing: m-v"
plot for [p=1:5] "Etot_vs_kgrid-script-new.dat_m-v" index p-1 u 3:5 w lp title item(p)
set nomulti

#plot \
#	'$SAVE'  u 1:2 w lp pt 7 lw 2  lc rgb "black" title "Total energy" 
#set yrange [GPVAL_DATA_Y_MIN-thres_10meV_per_atom:*]
#replot GPVAL_DATA_Y_MIN t "Min value" w l lt 4 dt 4 lc "red",\
#        GPVAL_DATA_Y_MIN+thres_1meV_per_atom w l lt 2 lc "blue" t "Min + 1meV/atom",\
#        GPVAL_DATA_Y_MIN+thres_10meV_per_atom w l lt 3 lc "magenta" t "Min + 10meV/atom"

pause -1
#set term pdfcairo enhanced
#set output "${SAVE}.pdf"
#replot

set term pngcairo enhanced size 900,500
set output "${SAVE}.png"
set multiplot layout 1,2
set object 1 rectangle from 1,Emin-thres_1mRy_per_atom to 13,Emin+thres_1mRy_per_atom fc "light-blue" fs transparent solid 0.4 noborder
set title "Smearing: gaussian"
plot for [p=1:5] "Etot_vs_kgrid-script-new.dat_gaussian" index p-1 u 3:5 w lp title item(p)
set title "Smearing: m-v"
plot for [p=1:5] "Etot_vs_kgrid-script-new.dat_m-v" index p-1 u 3:5 w lp title item(p)
set nomulti
replot

EOF


#Run the gnuplot script to make the plot of the total energy
gnuplot plot-smearing-script-new.gnu

exit

