#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`


for cutoff in 20 40 60; do
SAVE=Etot_vs_alat-script.dat_${cutoff}Ry
echo -e "# alat(bohr) energy(Ry)" > $SAVE

INVC=si_script.vc-relax.in
OUTVC=si_script.vc-relax.out.out_${cutoff}Ry

for alat in $(seq 10.10 0.01 10.30); do

IN=si_script.scf.in
OUT=si_script.scf.out

sed -e "s/ecutwfc   = 20/ecutwfc   = $cutoff/" -e "s/celldm(1) = 10.26/celldm(1) = $alat/" si.scf.in > $IN
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY=`cat $OUT | grep ! | tr -dc '0-9,-.'`
echo -e "$alat\t\t$ENERGY" >> $SAVE

done

sed -e "s/ecutwfc   = 20/ecutwfc   = $cutoff/" si.vc-relax.in > $INVC
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $INVC > $OUTVC"
$COMMAND < $INVC > $OUTVC


done

exit

#  ecutwfc   = 20

# self-consistent calculation
cat > $IN << EOF
&CONTROL
  calculation  = "scf",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  restart_mode = "from_scratch"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = $alat,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 5
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS {automatic}
4 4 4 1 1 1
EOF

#echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
#echo -e "\tEnd: " `date`


ENERGY=`cat $OUT | grep ! | tr -dc '0-9,-.'`
echo -e "$alat\t\t$ENERGY" >> $SAVE

#done

echo "Run completed at: " `date`
#echo "Now launch the run_plots script."
