#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVEVC=graphene_Etot_vc-relax_script.dat
echo -e "# cutoff(Ry) \t a(A) \t energy(Ry)" > $SAVEVC

for cutoff in 20 40 60 80 100 120; do

INVC=graphene_script.vc-relax.in
OUTVC=graphene_script.vc-relax.out_${cutoff}Ry

#2.46

sed -e "s/ecutwfc = 20/ecutwfc   = $cutoff/" graphene.vc-relax.in > $INVC
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $INVC > $OUTVC"
$COMMAND < $INVC > $OUTVC

ENERGY=$(grep -F "!" $OUTVC | tail -n 1 | awk '{print $5}')
alat=$(awk '/CELL_PARAMETERS/{gsub(/[()=]/," "); alat=$3; getline; scale=$1} END{printf "%.8f", alat*scale*0.52917721092}' $OUTVC )

echo -e "$cutoff\t\t$alat\t\t$ENERGY" >> $SAVEVC

done

