#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVE=Etot_vs_bond.dat
SAVEMAG=Mag_vs_bond.dat
SAVE2=Etot_vs_bond_eV.dat
echo -e "# bond(A) Energy(Ry)" > $SAVE
echo -e "# bond(A) abs. mag(bohr. mag)" > $SAVEMAG

for bondl in 0.7 0.8 0.9 1.0 1.1 1.11 1.113 1.12 1.13 1.2 1.3 1.5 1.7 2.0 2.2 2.4 2.6 2.8 3.0 3.4 4.0; do

xpos=`echo "$bondl + 2.0" | bc -l`

IN=co-script.scf.in
OUT=co-script.scf.out_bondl$bondl

# self-consistent calculation
cat > $IN << EOF
&CONTROL
  calculation  = "scf",
  prefix       = "CO",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  verbosity    = 'high'
  etot_conv_thr = 1.0D-4
  forc_conv_thr = 1.0D-3
/
&SYSTEM
  ibrav     = 0,
  nat       = 2,
  ntyp      = 2,
  nbnd      = 6,
  ecutwfc   = 60
  nspin     = 2
  occupations ='smearing',
  degauss     =0.001,
  starting_magnetization(1)=0.1
/
&ELECTRONS
  electron_maxstep=300
  conv_thr    = 1.D-7,
  mixing_beta = 0.5D0,
/
CELL_PARAMETERS {angstrom}
13.0  0.0  0.0
 0.0  8.0  0.0
 0.0  0.0  8.0
ATOMIC_SPECIES
O  1.00  O.pw-mt_fhi.UPF
C  1.00  C.pw-mt_fhi.UPF
ATOMIC_POSITIONS {angstrom}
C  $xpos  2.0  2.0   
O  2.000  2.0  2.0   
K_POINTS {Gamma}
EOF

#echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
#echo -e "\tEnd: " `date`


ENERGY=`cat $OUT | grep ! | tr -dc '0-9,-.'`
echo -e "$bondl\t\t$ENERGY" >> $SAVE

MAG=`cat $OUT | grep "absolute magnetization" | tail -1 | awk '{print $4}'`
echo -e "$bondl\t\t$MAG" >> $SAVEMAG

done

# Use the Emin for now
awk '{print $1,($2+43.25103045)*27.2114/2}' $SAVE > $SAVE2

echo "Run completed at: " `date`
