#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVE=EFermi-script.dat

#-------------------------------------------------#
# self-consistent calculation
#-------------------------------------------------#

IN=si_script.scf.in
OUT=si_script.scf.out

cat > $IN << EOF
&CONTROL
  calculation  = "scf",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  restart_mode = "from_scratch"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 10.21,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 5
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS {automatic}
8 8 8 1 1 1
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

# Check the VBM/CBM
echo "SCF calculation" > $SAVE
awk '/number of k points/{kpt=$5} /highest/{printf("K-points: %-8i Band edges %8.4f %8.4f Gap %8.4f\n", kpt, $7,$8,$8-$7)}' $OUT >> $SAVE
echo "NSCF calculation" >> $SAVE

#-------------------------------------------------#
# Non-self-consistent run, regular k-grid
#-------------------------------------------------#

for grid in 4 8 16 24; do

# Use unshifted grid for better comparison/alignment with band structure
klist="$grid $grid $grid 0 0 0"
#klist="$grid $grid $grid 1 1 1"
echo $klist

IN=si_script.nscf.in
OUT=si_script.nscf.out_k${grid}

cat > $IN << EOF
&CONTROL
  calculation  = "nscf",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  restart_mode = "from_scratch"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 10.21,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 10
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS {automatic}
$klist
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

# Check the VBM/CBM
awk '/number of k points/{kpt=$5} /highest/{printf("K-points: %-8i Band edges %8.4f %8.4f Gap %8.4f\n", kpt, $7,$8,$8-$7)}' $OUT >> $SAVE

#-------------------------------------------------#
# DOS calculation, regular k-grid and Gaussian smearing
#-------------------------------------------------#

IN=si_script.dos.in
OUT=si_script.dos.out
FILDOS=si_script.dos-kgrid${grid}.dat

# DOS without tetrahedra
cat > $IN << EOF
 &dos
   outdir='./tmp'
   prefix='Si'
   fildos="$FILDOS",
   degauss=0.01
   Emin=-10.0, Emax=20.0, DeltaE=0.1
 /
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/dos.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

#awk '/EFermi/{print "DOS,       EFermi= "$9}' $FILDOS >> $SAVE

#-------------------------------------------------#
# DOS calculation, with tetrahedra
#-------------------------------------------------#

IN=si_script.dos-tetra.in
OUT=si_script.dos-tetra.out
FILDOS=si_script.dos-tetra-kgrid${grid}.dat

# DOS with tetrahedra
cat > $IN << EOF
 &dos
   outdir='./tmp'
   prefix='Si'
   bz_sum="tetrahedra"
   fildos="$FILDOS",
   Emin=-10.0, Emax=20.0, DeltaE=0.1
 /
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/dos.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

#awk '/EFermi/{print "DOS tetra, EFermi= "$9}' $FILDOS >> $SAVE

done
awk '/EFermi/{print "DOS tetra, EFermi= "$9}' $FILDOS >> $SAVE

echo "Run completed at: " `date`

echo "Now launch the run_plots script."

exit




