#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

#SAVE=Etot_vs_kgrid-script2.dat
#SAVE0="${SAVE}0"
#SAVE1="${SAVE}1"
#echo -e "# N(NxNxN 000 grid) NKTOT energy(Ry)" > $SAVE0
#echo -e "# N(NxNxN 111 grid) NKTOT energy(Ry)" > $SAVE1


#-------------------------------------------------#
# self-consistent calculation
#-------------------------------------------------#

IN=si_script2.scf.in
OUT=si_script2.scf.out

cat > $IN << EOF
&CONTROL
  calculation  = "scf",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  restart_mode = "from_scratch"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 10.21,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 5
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS {automatic}
8 8 8 1 1 1
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

#-------------------------------------------------#
# Non-self-consistent run, regular k-grid
#-------------------------------------------------#

for grid in 4 8 16 24; do

klist="$grid $grid $grid 1 1 1"
echo $klist

IN=si_script2.nscf.in
OUT=si_script2.nscf.out_k${grid}

cat > $IN << EOF
&CONTROL
  calculation  = "nscf",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  restart_mode = "from_scratch"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 10.21,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 10
  occupations = "tetrahedra"
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS {automatic}
$klist
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

#-------------------------------------------------#
# DOS calculation, regular k-grid and Gaussian smearing
#-------------------------------------------------#

IN=si_script2.dos.in
OUT=si_script2.dos.out

# DOS without tetrahedra
cat > $IN << EOF
 &dos
   outdir='./tmp'
   prefix='Si'
   fildos='si_script2.dos-kgrid${grid}.dat',
   degauss=0.01
   Emin=-10.0, Emax=20.0, DeltaE=0.1
 /
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/dos.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

#-------------------------------------------------#
# DOS calculation, with tetrahedra
#-------------------------------------------------#

IN=si_script2.dos-tetra.in
OUT=si_script2.dos-tetra.out

# DOS with tetrahedra
cat > $IN << EOF
 &dos
   outdir='./tmp'
   prefix='Si'
   bz_sum="tetrahedra"
   fildos='si_script2.dos-tetra-kgrid${grid}.dat',
   Emin=-10.0, Emax=20.0, DeltaE=0.1
 /
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/dos.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`


done

echo "Run completed at: " `date`

echo "Now launch the run_plots script2."

exit




