#!/usr/bin/env bash

SAVE=Etot_vs_kgrid-script.dat
SAVE0="${SAVE}0"
SAVE1="${SAVE}1"

cat > plot-script.gnu <<EOF
#!/usr/bin/gnuplot

set term x11 enhanced

set xlabel "Number of k-points"
set ylabel "E_{tot} (Ry)"
Emin=-39.50280761
set xrange [0:200]

plot \
	'$SAVE0'  u 2:3 w lp pt 7 lw 2  lc rgb "black" title "E vs NxNxN 000",\
	'$SAVE0'  u 2:3:1 w labels offset char 1,1 notitle,\
	'$SAVE1'  u 2:3 w lp pt 7 lw 2  lc rgb "red" title "E vs NxNxN 111",\
	'$SAVE1'  u 2:3:1 w labels tc "red" offset char 1,-1 notitle,\
        Emin+(0.001*1) w l lt 1 dt 2 lc "green" t "+1 mRy/atom",\
        Emin-(0.001*1) w l lt 1 dt 2 lc "green" t "-1 mRy/atom"
pause -1
set term pdfcairo enhanced
set output "${SAVE}.pdf"
replot
set term pngcairo enhanced
set output "${SAVE}.png"
replot
EOF

gnuplot plot-script.gnu


exit




