#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVENAME=Etot_vs_kgrid-script-new.dat

# Loop over smearing
for smearing in gaussian m-v; do

# Set up separate files for the different smearing types
SAVE=${SAVENAME}_${smearing}
echo "Results saved to file $SAVE"
echo -e "# Sigma N\t\tNxNxN\t\tNKTOT\t\t energy(Ry)" > $SAVE

# Loop over sigma (smearing)
for sigma in 0.003 0.01 0.05 0.1 0.2; do

# Loop over k-point grid
#for grid in 3 6 9 12 15; do
for grid in 2 4 6 8 10 12 16; do

klist="$grid $grid $grid 1 1 1"
echo $klist

IN=al_script.scf.in
OUT=al_script_new.scf.out_k${grid}_g${sigma}_${smearing}

# self-consistent calculation
cat > $IN << EOF
&CONTROL
  calculation  = "scf",
  prefix       = "Al_bulk",
  pseudo_dir   = "../../Pseudo",
  outdir       = "./tmp",
  restart_mode = "from_scratch"
  verbosity    = "high"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 7.652448
  nat       = 1,
  ntyp      = 1,
  ecutwfc   = 20 
  ecutrho   = 200
  nbnd      = 5
                 occupations = 'smearing' ,
                     degauss = $sigma ,
                    smearing = '$smearing' ,
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Al  28.086  Al.pbe-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS {alat}
 Al 0.00 0.00 0.00
K_POINTS {automatic}
$klist
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`


ENERGY=`cat $OUT | grep ! | tr -dc '0-9,-.'`
KPOINTS=`cat $OUT | grep 'number of k points' | awk '{print $5}'`

klabel="${grid}x${grid}x1"
echo -e "$sigma\t$grid\t\t$klabel\t\t$KPOINTS\t\t$ENERGY" >> $SAVE

done
echo -e " " >> $SAVE
echo -e " " >> $SAVE
done
done
echo "Run completed at: " `date`
#echo "Now launch the run_plots script."

exit




