#!/usr/bin/env bash

SAVE=plot_script_pw2gw_kpts

cat > ${SAVE}.gnu <<EOF
#!/usr/bin/gnuplot

set term x11 enhanced

set title "pw2gw.x with shifted MP grid, acsplines smoothing"
set xlabel "Energy (eV)"
set ylabel "ɛ_2"
set xrange [0:10]
set yrange [0:100]
set xtics 1
set mxtics 5
set samples 2000
smooth=1000
plot 	\
     	"pw2gw_script_k8/epsTOT.dat" u 1:2:(smooth) t "8x8x8 (60)" smooth acsplines w l dt 1 lc "magenta",\
     	"pw2gw_script_k16/epsTOT.dat" u 1:2:(smooth) t "16x16x16 (408)" smooth acsplines w l dt 1 lc "cyan",\
     	"pw2gw_script_k32/epsTOT.dat" u 1:2:(smooth) t "32x32x32 (2992)" smooth acsplines w l dt 1 lc "red" lw 1,\
     	"pw2gw_script_k48/epsTOT.dat" u 1:2:(smooth) t "48x48x48 (9800)" smooth acsplines w l dt 1 lc "black" lw 1,\
     	"pw2gw_script_k48/epsTOT.dat" t "48x no smoothing" w l dt 1 lc "black" lw 0,\
	0 t "" w l lt 1 lc "black"

pause -1
set term pngcairo enhanced size 800,400
set output "${SAVE}.png"
replot
EOF

gnuplot ${SAVE}.gnu


exit




