#!/usr/bin/env bash

SAVEFORCE=Force_vs_bond-script.dat

cat > plot-force-script.gnu <<EOF
#!/opt/local/bin/gnuplot

# x11 should work on any system
# try wxt (ubuntu) or aqua (mac) for nicer plots
set term pngcairo enhanced size 600,400
set key bottom right
set output "${SAVEFORCE}.png"
set xlabel "Cell size (A)"
set ylabel "F_{tot} (Ry/au)
set xrange [1:1.3]
set key top right

plot \
	'$SAVEFORCE'  u 1:2 w lp pt 7 lw 2  lc rgb "black" title "Total force"

pause -1
set term x11
set out
replot
pause -1

EOF
gnuplot plot-force-script.gnu

exit

