#!/usr/bin/env bash

SAVE=scaling-script.dat			

#Print a gnuplot script to plot the 2 column files
cat > plot-scaling-script.gnu <<EOF
#!/usr/bin/gnuplot

# x11 should work on any system
# try wxt (ubuntu) or aqua (mac) for nicer plots
reset
set term pngcairo enhanced size 800,400
set output "scaling-script.png"

set xlabel "E_{cut} (Ry)"
set ylabel "N_{PW}"
set key top left

plot "Ref/dense.dat" u 1:(\$2/4) t "Calculated" w p pt 7 ps 1 lc "black",x**(3.0/2.0)*58 t "k x Ecut^{(3/2)}" w l  lc rgb "red"

EOF


#Run the gnuplot script to make the plot of the total energy
gnuplot plot-scaling-script.gnu

