#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

#-------------------------------
# self-consistent calculation
#-------------------------------
IN=graphene.scf-script.in
OUT=graphene.scf-script.out
cat > $IN << EOF
&CONTROL
    calculation       = 'scf'
    prefix            = 'graphene'
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
    restart_mode      = 'from_scratch'
    tstress           = .true.
    tprnfor           = .true.
    outdir            = './tmp'
    verbosity         = 'high'
    disk_io = 'minimal'
    wf_collect        = .true.
/
&SYSTEM
                       ibrav = 4,
                   celldm(1) = 4.635,
                   celldm(3) = 6,
                         nat = 2,
                        ntyp = 1,
                     ecutwfc = 40 ,
                        nbnd = 20,
                   !input_dft = 'bz-vbc' ,
                 occupations = 'smearing' ,
                     degauss = 0.03 ,
                    smearing = 'gaussian' ,
/
&ELECTRONS
                 mixing_beta = 0.7 ,
/
ATOMIC_SPECIES
    C   12.01100  C.pz-vbc.UPF 
ATOMIC_POSITIONS crystal 
    C      0.000000000    0.000000000    0.000000000    
    C      0.333333333    0.666666667    0.000000000    
K_POINTS automatic
 12 12 1	0 0 0
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x < $IN > $OUT"
echo -e "\t\t$COMMAND"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

#-------------------------------
# non-self-consistent bands calculation
#-------------------------------
IN=graphene.bands-script.in
OUT=graphene.bands-script.out
cat > $IN << EOF
&CONTROL
    calculation       = 'bands'
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
    prefix            = 'graphene'
    outdir            = './tmp'
    verbosity         = 'high'
    disk_io = 'minimal'
    wf_collect        = .true.
/
&SYSTEM
                       ibrav = 4,
                   celldm(1) = 4.635,
                   celldm(3) = 6,
                         nat = 2,
                        ntyp = 1,
                     ecutwfc = 40 ,
                        nbnd = 16,
                 occupations = 'smearing' ,
                     degauss = 0.03 ,
                    smearing = 'gaussian' ,
/
&ELECTRONS
                 mixing_beta = 0.7 ,
/
ATOMIC_SPECIES
    C   12.01100  C.pz-vbc.UPF 
ATOMIC_POSITIONS {crystal}
    C      0.000000000    0.000000000    0.000000000    
    C      0.333333333    0.666666667    0.000000000    
K_POINTS {crystal_b}
4
   0.0000000000     0.0000000000     0.0000000000 16 
   0.5000000000     0.0000000000     0.0000000000 16
   0.3333333333     0.3333333333     0.0000000000 16
   0.0000000000     0.0000000000     0.0000000000 1
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`


#-------------------------------
# bands postprocessing
#-------------------------------

IN=graphene.bandspp-script.in
OUT=graphene.bandspp-script.out
cat > $IN << EOF
&bands
    prefix = "graphene",
    outdir='./tmp'
    filband='graphene.bandspp.dat'
    lsym=.true.
 /
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/bands.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

#-------------------------------
# plot states postprocessing
#-------------------------------

IN=graphene.pp-script.in
OUT=graphene.pp-script.out
cat > $IN << EOF
&INPUTPP
prefix       = "graphene",
outdir       = "./tmp",
plot_num     = 7
filplot      = "psi2.plot"
kpoint       = 33
kband        = 4
lsign        =.false.
/
&PLOT
nfile     = 1
filepp(1) ="psi2.plot"
iflag     = 3
output_format = 5
fileout = "psi2_k33_b4.xsf"
/
EOF

COMMAND="$BIN_DIR/pp.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

cat > $IN << EOF
&INPUTPP
prefix       = "graphene",
outdir       = "./tmp",
plot_num     = 7
filplot      = "psi2.plot"
kpoint       = 1
kband        = 4
lsign        =.false.
/
&PLOT
nfile     = 1
filepp(1) ="psi2.plot"
iflag     = 3
output_format = 5
fileout = "psi2_k1_b4.xsf"
/
EOF

COMMAND="$BIN_DIR/pp.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

#-------------------------------
# plotband postprocessing
#-------------------------------

IN=graphene.plotband-script.in
OUT=graphene.plotband-script.out
cat > $IN << EOF
graphene.bandspp.dat
-6.0 10.0

graphene.bandspp.ps
6.377
1 6.377
EOF

echo -e "\tStart: " `date`
COMMAND="$BIN_DIR/plotband.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

echo -e "\tRunning gnuplot script: " `date`
gnuplot graphene.bandspp.gnuplot

echo "Run completed at: " `date`



exit




