#!/usr/bin/env bash

SAVE=Etot_vs_Ecut-script.dat			
GAP=Gap_vs_Ecut-script.dat

#Print a gnuplot script to plot the 2 column files
cat > plot-energy-script.gnu <<EOF
#!/usr/bin/gnuplot

# x11 should work on any system
# try wxt (ubuntu) or aqua (mac) for nicer plots
set term x11 enhanced
set out

set xlabel "E_{cut} (Ry)"
set ylabel "E_{tot} (Ry)
thres_1mRy_per_atom=0.001*2
thres_10mRy_per_atom=0.01*2

plot \
	'$SAVE'  u 1:2 w lp pt 7 lw 2  lc rgb "black" title "Total energy" 
set yrange [GPVAL_DATA_Y_MIN-thres_10mRy_per_atom:GPVAL_DATA_Y_MIN+thres_10mRy_per_atom*10]
replot GPVAL_DATA_Y_MIN t "Min value" w l lt 4 dt 4 lc "red",\
        GPVAL_DATA_Y_MIN+thres_1mRy_per_atom w l lt 2 lc "blue" t "Min + 1mRy/atom",\
        GPVAL_DATA_Y_MIN+thres_10mRy_per_atom w l lt 3 lc "magenta" t "Min + 10mRy/atom"

pause -1
set term pdfcairo enhanced
set output "${SAVE}.pdf"
replot
set term pngcairo enhanced size 600,400
set output "${SAVE}.png"
replot

EOF


#Run the gnuplot script to make the plot of the total energy
gnuplot plot-energy-script.gnu

exit

